spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:consumer-kafka.yml
      - classpath:consumer-server.yml

  application:
    name: ${APP_SERVICE_NAME:kafka-consumer}